#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <set>
#include <functional>
#include <fstream>
#include "../includes/scanner.h"
namespace HLex
{
    using std::map;
    using std::vector;
    using char_type = char;
    void print_line(const std::string &s, int &pos)
    {
        int cnt = 100;
        while (pos < s.size() && cnt)
        {
            std::cout << s[pos++];
            cnt--;
        }
        std::cout.flush();
    }
    class Lexer
    {
    public:
        Lexer(const std::string &con);
        std::vector<Token> lex()
        {
            std::vector<Token> ret;
            int cur_state = entry;
            // to roll back state tag val
            std::vector<std::pair<int, Token>> pos_stac;
            // str pos
            int pos = 0;
            std::string cur_token;
            std::string cur_tag;

            while (pos < content.size())
            {
                if (tab[cur_state].count(content[pos]))
                {
                    cur_state = tab[cur_state][content[pos]];
                    cur_token += content[pos];

                    if (fin_stat_tab.count(cur_state))
                    {
                        if (fin_stat_tab[cur_state] != "")
                            cur_tag = fin_stat_tab[cur_state];

                        pos_stac.clear();
                        pos_stac.push_back({pos + 1, {cur_tag, cur_token}});
                    }
                    pos++;
                }
                else
                {
                    if (pos_stac.empty())
                    {
                        print_line(content, pos);
                        throw std::runtime_error(" LexerGenerator::lex: Lexer Error");
                    }
                    auto [p, tok] = pos_stac.back();
                    // if a symbol is a keyword pr ignore
                    auto val = tok.val;
                    if (keywords.count(val))
                        tok = Token{keywords[val], val};
                    if (user_defs.count(tok.tag))
                    {
                        p -= tok.val.size();
                        tok.val = user_defs[tok.tag](content, p);
                    }
                    if (!ignore.count(tok.tag))
                        ret.push_back(tok);

                    // roll back
                    pos = p;
                    cur_state = entry;
                    cur_token = cur_tag = "";
                    pos_stac.clear();
                }
            }
            if (pos_stac.size())
                ret.push_back(pos_stac.back().second);
            return ret;
        }

    private:
        std::string content;
        int pos = 0;

        std::map<std::string, std::string> keywords;
        std::map<std::string, std::function<std::string(const std::string &, int &)>> user_defs;
        std::set<std::string> ignore;

        int entry;
        map<int, std::string> fin_stat_tab;
        vector<map<char_type, int>> tab;
    };

    std::string read_file(const std::string &filename)
    {
        std::ifstream ifs(filename, std::ios::in | std::ios::binary);
        if (!ifs)
            throw std::runtime_error("open file " + filename + " failed\n");
        char *file_content;
        ifs.seekg(0, std::ios::end);
        size_t file_length = ifs.tellg();
        ifs.seekg(0, std::ios::beg);

        file_content = new char[file_length];

        ifs.read(file_content, file_length);
        ifs.close();

        std::string str(file_content, file_content + file_length);
        delete[] file_content;
        return str;
    }
}
// Following code is generated by program
namespace HLex
{
    Lexer::Lexer(const std::string &con) : content(con), entry(8)
    {
        fin_stat_tab = {{1, "colon"}, {2, "newline"}, {3, "nterminal"}, {4, "or"}, {5, "semi"}, {6, "space"}, {7, "terminal"}};
        tab = {{{'A', 11}, {'B', 11}, {'C', 11}, {'D', 11}, {'E', 11}, {'F', 11}, {'G', 11}, {'H', 11}, {'I', 11}, {'J', 11}, {'K', 11}, {'L', 11}, {'M', 11}, {'N', 11}, {'O', 11}, {'P', 11}, {'Q', 11}, {'R', 11}, {'S', 11}, {'T', 11}, {'U', 11}, {'V', 11}, {'W', 11}, {'X', 11}, {'Y', 11}, {'Z', 11}}, {}, {}, {}, {}, {}, {}, {}, {{'\t', 6}, {'\n', 2}, {'\r', 9}, {' ', 6}, {':', 1}, {';', 5}, {'<', 10}, {'[', 0}, {'|', 4}}, {{'\n', 2}}, {{'0', 12}, {'1', 12}, {'2', 12}, {'3', 12}, {'4', 12}, {'5', 12}, {'6', 12}, {'7', 12}, {'8', 12}, {'9', 12}, {'A', 12}, {'B', 12}, {'C', 12}, {'D', 12}, {'E', 12}, {'F', 12}, {'G', 12}, {'H', 12}, {'I', 12}, {'J', 12}, {'K', 12}, {'L', 12}, {'M', 12}, {'N', 12}, {'O', 12}, {'P', 12}, {'Q', 12}, {'R', 12}, {'S', 12}, {'T', 12}, {'U', 12}, {'V', 12}, {'W', 12}, {'X', 12}, {'Y', 12}, {'Z', 12}, {'a', 12}, {'b', 12}, {'c', 12}, {'d', 12}, {'e', 12}, {'f', 12}, {'g', 12}, {'h', 12}, {'i', 12}, {'j', 12}, {'k', 12}, {'l', 12}, {'m', 12}, {'n', 12}, {'o', 12}, {'p', 12}, {'q', 12}, {'r', 12}, {'s', 12}, {'t', 12}, {'u', 12}, {'v', 12}, {'w', 12}, {'x', 12}, {'y', 12}, {'z', 12}}, {{'A', 11}, {'B', 11}, {'C', 11}, {'D', 11}, {'E', 11}, {'F', 11}, {'G', 11}, {'H', 11}, {'I', 11}, {'J', 11}, {'K', 11}, {'L', 11}, {'M', 11}, {'N', 11}, {'O', 11}, {'P', 11}, {'Q', 11}, {'R', 11}, {'S', 11}, {'T', 11}, {'U', 11}, {'V', 11}, {'W', 11}, {'X', 11}, {'Y', 11}, {'Z', 11}, {']', 3}}, {{'0', 12}, {'1', 12}, {'2', 12}, {'3', 12}, {'4', 12}, {'5', 12}, {'6', 12}, {'7', 12}, {'8', 12}, {'9', 12}, {'>', 7}, {'A', 12}, {'B', 12}, {'C', 12}, {'D', 12}, {'E', 12}, {'F', 12}, {'G', 12}, {'H', 12}, {'I', 12}, {'J', 12}, {'K', 12}, {'L', 12}, {'M', 12}, {'N', 12}, {'O', 12}, {'P', 12}, {'Q', 12}, {'R', 12}, {'S', 12}, {'T', 12}, {'U', 12}, {'V', 12}, {'W', 12}, {'X', 12}, {'Y', 12}, {'Z', 12}, {'a', 12}, {'b', 12}, {'c', 12}, {'d', 12}, {'e', 12}, {'f', 12}, {'g', 12}, {'h', 12}, {'i', 12}, {'j', 12}, {'k', 12}, {'l', 12}, {'m', 12}, {'n', 12}, {'o', 12}, {'p', 12}, {'q', 12}, {'r', 12}, {'s', 12}, {'t', 12}, {'u', 12}, {'v', 12}, {'w', 12}, {'x', 12}, {'y', 12}, {'z', 12}}};
        ignore = {"space"};
        keywords = {};
        user_defs = {};
    }
    Scanner scanner(const std::string &str)
    {
        Lexer L(str);
        Scanner ret;
        ret.data = L.lex();
        return ret;
    }
}